version: '3.8'
services:
  web:
    image: nginx:latest
    ports:
      - "8011:80"
    working_dir: /code
    restart: on-failure
    depends_on:
      - php
    volumes:
      - ./:/code
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - internal

  php:
    build:
      context: ./docker/php
    restart: on-failure
    working_dir: /code
    volumes:
      - ./:/code
    depends_on:
      - postgres
    networks:
      - internal
      
  postgres:
    image: postgres:13.9
    restart: on-failure
    environment:
      POSTGRES_DB: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    ports:
      - '5432:5432'
    networks:
      - internal

volumes:
  db-data:
networks:
  internal:
    driver: bridge


